### ISSUE TITLE
Remove Bootstrap 3 (js, css, less ...)

### ISSUE THREAD

**Issue by GHSVS-de** [GHSVS-de/plg_system_bs3ghsvs#12]
Because the WebAssetManager in Joomla 4 is a complete B\C breaker the base idea of this plugin is dead. Therefore we can remove alternative versions. Check also JQuery.

**Comment by ReLater** [comment]
Done: https://github.com/GHSVS-de/plg_system_bs3ghsvs/commit/1cfd0d73fbb12b7c61204d4012f71c97f3e49882
